// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCCNLfI3RZkMm64yoeHPbn3PYnHifPrxs',
    appId: '1:510240997460:web:ffe6b3bf95593384976dc1',
    messagingSenderId: '510240997460',
    projectId: 'flutterfirebaselearn-3b9d2',
    authDomain: 'flutterfirebaselearn-3b9d2.firebaseapp.com',
    storageBucket: 'flutterfirebaselearn-3b9d2.firebasestorage.app',
    measurementId: 'G-JHESKTK88T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApz4JK4l0gkvT2pwGCjXVEr6LwZPmGGU0',
    appId: '1:510240997460:android:96daabb32c33191a976dc1',
    messagingSenderId: '510240997460',
    projectId: 'flutterfirebaselearn-3b9d2',
    storageBucket: 'flutterfirebaselearn-3b9d2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCaBnHwZ6t2TT1kfWIwLjGOFCo2Jmywc3c',
    appId: '1:510240997460:ios:0406c914397dd158976dc1',
    messagingSenderId: '510240997460',
    projectId: 'flutterfirebaselearn-3b9d2',
    storageBucket: 'flutterfirebaselearn-3b9d2.firebasestorage.app',
    iosBundleId: 'com.example.flutterWithFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCaBnHwZ6t2TT1kfWIwLjGOFCo2Jmywc3c',
    appId: '1:510240997460:ios:0406c914397dd158976dc1',
    messagingSenderId: '510240997460',
    projectId: 'flutterfirebaselearn-3b9d2',
    storageBucket: 'flutterfirebaselearn-3b9d2.firebasestorage.app',
    iosBundleId: 'com.example.flutterWithFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDCCNLfI3RZkMm64yoeHPbn3PYnHifPrxs',
    appId: '1:510240997460:web:0fbea0372aca9904976dc1',
    messagingSenderId: '510240997460',
    projectId: 'flutterfirebaselearn-3b9d2',
    authDomain: 'flutterfirebaselearn-3b9d2.firebaseapp.com',
    storageBucket: 'flutterfirebaselearn-3b9d2.firebasestorage.app',
    measurementId: 'G-LRW6NEBFSW',
  );
}
